services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER}
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-volumes:/data
volumes:
  mysql-volume:
  redis-volumes:
